imagePullSecrets: []

db:
  # Configure the database for all microservices.
  # Currently only mongo is supported but this 
  # boilerplate exists nonetheless.
  driver: "" # mongo | postgres
  postgres:
    host:
      value: ""
    port:
      value: ""
    database:
      value: ""
    username:
      value: ""
    password:
      value: ""
    sslmode:
      value: ""
    ca:
      value: ""
  mongo:
    host:
      value: ""
    dbName:
      value: ""
    authSource:
      value: ""
    username:
      value: ""
    password:
      value: ""

s3:
  endpoint: ""
  region: us-west-2
  bucket: ""
  thumbnailBucket: ""
  accessKeyId:
    value: ""
  secretAccessKey:
    value: ""

prometheus:
  enabled: false

aws:
  region: us-east-1
  accessKeyId:
    value: ""
  secretAccessKey:
    value: ""

transcriber:
  streamKey:
    value: ""
  specialty: RADIOLOGY
  image: thavlik/transcriber:latest
  imagePullPolicy: Always
  logLevel: debug
  resources: {}

app:
  enabled: true
  image: thavlik/transcriber-app:latest
  imagePullPolicy: Always
  replicas: 1
  resources: {}

imgsearch:
  enabled: true
  metaCollectionName: images
  bing:
    location:
      value: global
    endpoint:
      value: https://api.bing.microsoft.com/
    apiKey:
      value: ""
  image: thavlik/imgsearch:latest
  imagePullPolicy: Always
  replicas: 1
  resources: {}
  logLevel: debug
