{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}-gateway
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
  - name: http
    port: 80
{{- end }}
