{{- if .Values.comprehend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-comprehend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-comprehend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-comprehend
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: server
        imagePullPolicy: {{ .Values.comprehend.imagePullPolicy }}
        image: {{ .Values.comprehend.image }}
    {{- if .Values.comprehend.resources }}
        resources:
{{ toYaml .Values.comprehend.resources | indent 10 }}
    {{- end }}
        command:
          - comprehend
          - server
        {{- if .Values.prometheus.enabled }}
          - --metrics-port
          - "2112"
        {{- end }}
        ports:
        - containerPort: 80
          name: http
      {{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
      {{- end }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.comprehend.logLevel }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: AWS_ACCESS_KEY_ID
{{ tpl (toYaml .Values.aws.accessKeyId) . | indent 10 }}
        - name: AWS_SECRET_ACCESS_KEY
{{ tpl (toYaml .Values.aws.secretAccessKey) . | indent 10 }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
{{- end }}
