{{- if .Values.pharmaseer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pharmaseer
spec:
  replicas: {{ .Values.pharmaseer.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pharmaseer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pharmaseer
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: server
        imagePullPolicy: {{ .Values.pharmaseer.imagePullPolicy }}
        image: {{ .Values.pharmaseer.image }}
    {{- if .Values.pharmaseer.resources }}
        resources:
{{ toYaml .Values.pharmaseer.resources | indent 10 }}
    {{- end }}
        command:
          - pharmaseer
          - server
          - --db-driver
          - {{ required "missing db.driver" .Values.db.driver }}
          - --pdb-bucket
          - {{ required "missing pharmaseer.pdbBucket" .Values.pharmaseer.pdbBucket }}
          - --svg-bucket
          - {{ required "missing pharmaseer.svgBucket" .Values.pharmaseer.svgBucket }}
        {{- if .Values.prometheus.enabled }}
          - --metrics-port
          - "2112"
        {{- end }}
        ports:
        - containerPort: 80
          name: http
      {{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
      {{- end }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.pharmaseer.logLevel }}
      {{- if .Values.s3.endpoint }}
        - name: S3_ENDPOINT
          value: {{ .Values.s3.endpoint }}
      {{- end }}
        - name: AWS_REGION
          value: {{ .Values.s3.region }}
        - name: AWS_ACCESS_KEY_ID
{{ tpl (toYaml .Values.s3.accessKeyId) . | indent 10 }}
        - name: AWS_SECRET_ACCESS_KEY
{{ tpl (toYaml .Values.s3.secretAccessKey) . | indent 10 }}
        - name: BING_API_KEY
{{ tpl (toYaml .Values.bing.apiKey) . | indent 10 }}
        - name: BING_LOCATION
{{ tpl (toYaml .Values.bing.location) . | indent 10 }}
        - name: BING_ENDPOINT
{{ tpl (toYaml .Values.bing.endpoint) . | indent 10 }}
      {{- if .Values.redis.enabled }}
        - name: REDIS_USERNAME
{{ tpl (toYaml .Values.redis.username) . | indent 10 }}
        - name: REDIS_PASSWORD
{{ tpl (toYaml .Values.redis.password) . | indent 10 }}
        - name: REDIS_HOST
{{ tpl (toYaml .Values.redis.host) . | indent 10 }}
        - name: REDIS_PORT
{{ tpl (toYaml .Values.redis.port) . | indent 10 }}
      {{- end }}
{{- if eq .Values.db.driver "postgres" }}
        - name: POSTGRES_DATABASE
{{ tpl (toYaml .Values.db.postgres.database) . | indent 10 }}
        - name: POSTGRES_HOST
{{ tpl (toYaml .Values.db.postgres.host) . | indent 10 }}
        - name: POSTGRES_PORT
{{ tpl (toYaml .Values.db.postgres.port) . | indent 10 }}
        - name: POSTGRES_USERNAME
{{ tpl (toYaml .Values.db.postgres.username) . | indent 10 }}
        - name: POSTGRES_PASSWORD
{{ tpl (toYaml .Values.db.postgres.password) . | indent 10 }}
        - name: POSTGRES_CA_CERT
{{ tpl (toYaml .Values.db.postgres.ca) . | indent 10 }}
        - name: POSTGRES_SSL_MODE
{{ tpl (toYaml .Values.db.postgres.sslmode) . | indent 10 }}
{{- else if eq .Values.db.driver "mongo" }}
        - name: MONGO_DB_NAME
{{ tpl (toYaml .Values.db.mongo.dbName) . | indent 10 }}
        - name: MONGO_AUTH_SOURCE
{{ tpl (toYaml .Values.db.mongo.authSource) . | indent 10 }}
        - name: MONGO_HOST
{{ tpl (toYaml .Values.db.mongo.host) . | indent 10 }}
        - name: MONGO_USERNAME
{{ tpl (toYaml .Values.db.mongo.username) . | indent 10 }}
        - name: MONGO_PASSWORD
{{ tpl (toYaml .Values.db.mongo.password) . | indent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
{{- end }}
