{{- if .Values.strim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-strim
  labels:
    app: {{ .Release.Name }}-strim
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-strim
  ports:
  - name: rtmp
    port: 1935
{{- end }}
