apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-transcriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-transcriber
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-transcriber
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: transcriber
        imagePullPolicy: {{ .Values.transcriber.imagePullPolicy }}
        image: {{ .Values.transcriber.image }}
    {{- if .Values.transcriber.resources }}
        resources:
{{ toYaml .Values.transcriber.resources | indent 10 }}
    {{- end }}
        command:
          - transcriber
          - server
        {{- if .Values.prometheus.enabled }}
          - --metrics-port
          - "2112"
        {{- end }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 1935
          name: rtmp
      {{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
      {{- end }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.transcriber.logLevel }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: AWS_ACCESS_KEY_ID
{{ tpl (toYaml .Values.aws.accessKeyId) . | indent 10 }}
        - name: AWS_SECRET_ACCESS_KEY
{{ tpl (toYaml .Values.aws.secretAccessKey) . | indent 10 }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80