apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transcriber
  labels:
    app: {{ .Release.Name }}-transcriber
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-transcriber
  ports:
  - name: http
    port: 80
